### PR TITLE
Fix installation instructions given new location of Wflow source directory

### LINKED ISSUE #584: Check install docs
Because of #576 check if install docs are up to date.

### PR DESCRIPTION
**Pull request by JoostBuitink**
## Issue addressed
Fixes #584 and #265 and #333

## Explanation
Explain how you addressed the bug/feature request, what choices you made and why.

## Checklist
- [ ] Updated tests or added new tests
- [ ] Branch is up to date with `master`
- [ ] Tests & pre-commit hooks pass
- [x] Updated documentation if needed
- [x] Updated changelog.qmd if needed

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

### CODE REVIEW

File: Wflow/src/soil/soil.jl [hunk 1]
```diff
@@ -360,6 +360,7 @@ function SbmSoilParameters(
         cum_depth_layers = pushfirst(cumsum(soil_layer_thickness), 0.0)
         maxlayers = 1
     end
+    @info "Using `$maxlayers` soil layers with the following thickness: `$soil_layer_thickness`"
```
Comment (vers-w) [inline Wflow/src/soil/soil.jl:363]: Nice to add this info log message!
 
Code lines 359 and 360 should be removed here. The info message can be moved to the section below the `if` statement. As `soil_layer_thickness` contains a `NaN` value maybe better to log here only the `config_soil_layer_thickness` info and number of layers based on that (`maxlayers` - 1)? And maybe add another info message below the `else` statement?

**Review by vers-w — COMMENTED** [review]
Just one small code suggestion.

Additionally, I noticed that in de code:
https://github.com/Deltares/Wflow.jl/blob/docs/fix-install/Wflow/src/soil/soil.jl#L763 
https://github.com/Deltares/Wflow.jl/blob/docs/fix-install/Wflow/src/soil/soil.jl#L785
soil evaporation for one layer can be removed.

In the docs soil evaporation for one layer can also be removed:
https://github.com/Deltares/Wflow.jl/blob/docs/fix-install/docs/model_docs/land/landhydrology_sbm.qmd#L398

As the soil is always split-up into different layers, the first part of the sentence can be removed here:
https://github.com/Deltares/Wflow.jl/blob/docs/fix-install/docs/model_docs/land/landhydrology_sbm.qmd#L985

Probably good to rewrite this a bit as it is not an option anymore:
https://github.com/Deltares/Wflow.jl/blob/docs/fix-install/docs/model_docs/land/landhydrology_sbm.qmd#L15

File: docs/model_docs/land/landhydrology_sbm.qmd [hunk 2]
```diff
@@ -397,13 +397,15 @@ covered by a glacier.
 
 ### Bare soil evaporation
 
-If there is only one soil layer present in the `SBM` `soil` model, the bare soil evaporation
-is scaled according to the wetness of the soil layer. The fraction of bare soil is assumed
-to be equal to the fraction not covered by the canopy gap fraction corrected by the total
-water fraction and glacier fraction. When the soil is fully saturated, evaporation is set to
```
Comment (vers-w) [inline docs/model_docs/land/landhydrology_sbm.qmd:403]: LGTM! One final comment: good to leave this sentence in the docs: "The fraction of bare soil....glacier fraction. "

**Review by vers-w — APPROVED** [review]
