### PR TITLE
Fix mass balance subsurface flow at sub-daily model time step

### LINKED ISSUE #724: Mass balance at sub-daily time step for subsurface flow not corrrect
This is the case for `LateralSSF` and `UnconfinedAquifer` subsurface flow concepts. At a sub-daily model time step the units of different variables to compute the water mass balance do not match.

### PR DESCRIPTION
**Pull request by vers-w**
## Issue addressed
Fixes #724 

Also addressed some review comments from https://github.com/Deltares/Wflow.jl/pull/713.

### CODE REVIEW

File: Wflow/src/mass_balance.jl [hunk 1]
```diff
@@ -56,7 +56,8 @@ function HydrologicalMassBalance(domain::Domain, config::Config)
         else
             river_water_balance = MassBalance(; n = n_river)
         end
-        routing = FlowRoutingMassBalance(;
+        args = (river_water_balance, reservoir_water_balance)
+        routing = FlowRoutingMassBalance{typeof.(args)...}(;
```
Comment (SouthEndMusic) [inline Wflow/src/mass_balance.jl]: Why do you need this? I'm pretty sure the default constructor can figure out the type parameters automatically

Comment (vers-w) [reply Wflow/src/mass_balance.jl]: Yeah, I agree, the default constructor can figure this out, removed `args`.
