### PR TITLE
Fix failing soil tests

### LINKED ISSUE #883: Fix failing soil tests
Just to have an issue associated with https://github.com/Deltares/Wflow.jl/pull/874.

### PR DESCRIPTION
**Pull request by SouthEndMusic**
Fixes https://github.com/Deltares/Wflow.jl/issues/883.

Follow up of failing tests after merging https://github.com/Deltares/Wflow.jl/pull/845 and https://github.com/Deltares/Wflow.jl/pull/854

### CODE REVIEW

File: Wflow/src/sediment/sediment_transport/land_to_river.jl [hunk 1]
```diff
@@ -24,26 +24,26 @@ end
...
+    sediment_to_river_model = SedimentToRiverModel(; n)
+    return sediment_to_river_model
 end
 
 "Update total sediment reaching the river model boundary conditions"
 function update_bc_sediment_to_river_model!(
-    to_river_model::SedimentToRiverModel,
-    transport_model::SedimentLandTransportModel,
+    sediment_to_river_model::SedimentToRiverModel,
+    sediment_flux_model::SedimentLandTransportModel,
```
Comment (vers-w) [inline Wflow/src/sediment/sediment_transport/land_to_river.jl]: Suggest to keep the name closer to `SedimentLandTransportModel`:
```suggestion
    sediment_transport_model::SedimentLandTransportModel,
```

File: Wflow/src/sediment/sediment_transport/land_to_river.jl [hunk 2]
```diff
@@ -93,32 +93,32 @@ end
...
+    sediment_to_river_model = SedimentToRiverDifferentiationModel(; n)
+    return sediment_to_river_model
 end
 
 "Update differentiated sediment reaching the river model boundary conditions"
 function update_bc_sediment_to_river_model!(
-    to_river_model::SedimentToRiverDifferentiationModel,
-    transport_model::SedimentLandTransportDifferentiationModel,
+    sediment_to_river_model::SedimentToRiverDifferentiationModel,
+    sediment_flux_model::SedimentLandTransportDifferentiationModel,
```
Comment (vers-w) [inline Wflow/src/sediment/sediment_transport/land_to_river.jl]:
```suggestion
    sediment_transport_model::SedimentLandTransportDifferentiationModel,
```

File: Wflow/src/sediment/sediment_transport/overland_flow_transport.jl [hunk 3]
```diff
@@ -28,8 +28,8 @@ end
 "Initialize total sediment flux in overland flow model"
 function SedimentLandTransportModel(indices::Vector{CartesianIndex{2}})
     n = length(indices)
-    model = SedimentLandTransportModel(; n)
-    return model
+    sediment_flux_model = SedimentLandTransportModel(; n)
```
Comment (vers-w) [inline Wflow/src/sediment/sediment_transport/overland_flow_transport.jl]:
```suggestion
    sediment_transport_model = SedimentLandTransportModel(; n)
```

File: Wflow/src/sediment/sediment_transport/overland_flow_transport.jl [hunk 4]
```diff
@@ -125,8 +125,8 @@ end
 "Initialize differentiated sediment flux in overland flow model"
 function SedimentLandTransportDifferentiationModel(indices::Vector{CartesianIndex{2}})
     n = length(indices)
-    model = SedimentLandTransportDifferentiationModel(; n)
-    return model
+    sediment_flux_model = SedimentLandTransportDifferentiationModel(; n)
```
Comment (vers-w) [inline Wflow/src/sediment/sediment_transport/overland_flow_transport.jl]:
```suggestion
    sediment_transport_model = SedimentLandTransportDifferentiationModel(; n)
```

File: Wflow/src/sediment/sediment_transport/river_transport.jl [hunk 5]
```diff
@@ -244,16 +244,16 @@ function SedimentRiverTransportModel(
     n = length(indices)
 
     parameters = SedimentRiverTransportParameters(dataset, config, indices)
-    model = SedimentRiverTransportModel(; n, parameters)
-    return model
+    sediment_flux_model = SedimentRiverTransportModel(; n, parameters)
```
Comment (vers-w) [inline Wflow/src/sediment/sediment_transport/river_transport.jl]:
```suggestion
    sediment_transport_model = SedimentRiverTransportModel(; n, parameters)
```

File: Wflow/src/sediment/sediment_transport/river_transport.jl [hunk 6]
```diff
@@ -909,8 +910,8 @@ function SedimentConcentrationsRiverModel(
 )
     n = length(indices)
     parameters = SedimentConcentrationsRiverParameters(dataset, config, indices)
-    model = SedimentConcentrationsRiverModel(; n, parameters)
-    return model
+    concentrations_model = SedimentConcentrationsRiverModel(; n, parameters)
```
Comment (vers-w) [inline Wflow/src/sediment/sediment_transport/river_transport.jl]:
```suggestion
    sediment_concentration_model = SedimentConcentrationsRiverModel(; n, parameters)
```

File: Wflow/test/sediment.jl [hunk 7]
```diff
@@ -258,7 +258,7 @@ end
 
 @testitem "unit: update SedimentConcentrationsRiverModel" begin
     n = 1
-    concentration = Wflow.SedimentConcentrationsRiverModel(;
+    concentrations_model = Wflow.SedimentConcentrationsRiverModel(;
```
Comment (vers-w) [inline Wflow/test/sediment.jl]:
```suggestion
    sediment_concentration_model = Wflow.SedimentConcentrationsRiverModel(;
```

File: Wflow/test/soil.jl [hunk 8]
```diff
@@ -35,11 +35,11 @@
         ),
         boundary_conditions = Wflow.OpenWaterRunoffBC(; n, water_flux_surface = [7.5e-3]),
     )
-    demand = Wflow.Demand(;
-        domestic = Wflow.NoDemand(; n),
-        industry = Wflow.NoDemand(; n),
-        livestock = Wflow.NoDemand(; n),
-        paddy = Wflow.Paddy(;
+    demand = Wflow.DemandModel(;
```
Comment (vers-w) [inline Wflow/test/soil.jl:41]:
```suggestion
    demand_model = Wflow.DemandModel(;
```

File: Wflow/test/soil.jl [hunk 9]
```diff
@@ -51,11 +51,11 @@
             ),
             variables = Wflow.PaddyVariables(; n, h = [1e-5], evaporation = [4e-3]),
         ),
-        nonpaddy = Wflow.NoIrrigationNonPaddy(n),
+        nonpaddy = Wflow.NoIrrigationNonPaddyModel(n),
```
Comment (vers-w) [inline Wflow/test/soil.jl:46]:
```suggestion
        nonpaddy_model = Wflow.NoIrrigationNonPaddyModel(n),
```

File: Wflow/test/soil.jl [hunk 10]
```diff
@@ -51,11 +51,11 @@
...
         variables = Wflow.DemandVariables(; n),
     )
 
-    allocation = Wflow.AllocationLand(;
+    allocation = Wflow.AllocationLandModel(;
```
Comment (vers-w) [inline Wflow/test/soil.jl]:
```suggestion
    allocation_model = Wflow.AllocationLandModel(;
```

File: Wflow/test/soil.jl [hunk 11]
```diff
@@ -253,11 +253,11 @@ end
     )
 
     runoff = (; variables = (; runoff_land = [0.0], ae_openw_l = [0.0]))
-    demand = Wflow.Demand(;
-        domestic = Wflow.NoDemand(; n),
-        industry = Wflow.NoDemand(; n),
-        livestock = Wflow.NoDemand(; n),
-        paddy = Wflow.Paddy(;
+    demand = Wflow.DemandModel(;
```
Comment (vers-w) [inline Wflow/test/soil.jl:260]:
```suggestion
    demand_model = Wflow.DemandModel(;
```

File: Wflow/test/soil.jl [hunk 12]
```diff
@@ -269,7 +269,7 @@ end
             ),
             variables = Wflow.PaddyVariables(; n, h = [1e-5], evaporation = [4e-3]),
         ),
-        nonpaddy = Wflow.NoIrrigationNonPaddy(n),
+        nonpaddy = Wflow.NoIrrigationNonPaddyModel(n),
```
Comment (vers-w) [inline Wflow/test/soil.jl:265]:
```suggestion
        nonpaddy_model = Wflow.NoIrrigationNonPaddyModel(n),
```

**Review by vers-w — CHANGES_REQUESTED** [review]
Couple of renaming suggestions.

File: Wflow/test/soil.jl
Comment (vers-w) [inline Wflow/test/soil.jl]: Suggest to use here common/default parameter values.

Comment (vers-w) [inline Wflow/test/soil.jl]: Suggest to use here common/default parameter values.

File: Wflow/test/soil.jl (hunk 9 above)
Comment (SouthEndMusic) [reply Wflow/test/soil.jl:46]: That doesn't work since the field is called `nonpaddy`

File: Wflow/test/soil.jl (hunk 10 above)
Comment (SouthEndMusic) [reply Wflow/test/soil.jl]: That doesn't work because `update_bc_soil_model!` expects `allocation` as an external model

File: Wflow/test/soil.jl (hunk 8 above)
Comment (SouthEndMusic) [reply Wflow/test/soil.jl:41]: That doesn't work because `update_bc_soil_model!` expects `demand` as an external model

File: Wflow/test/soil.jl (hunk 11 above)
Comment (SouthEndMusic) [reply Wflow/test/soil.jl:260]: That doesn't work because `update_soil_water_storage!` expects `demand` as an external model

File: Wflow/test/soil.jl (hunk 12 above)
Comment (SouthEndMusic) [reply Wflow/test/soil.jl:265]: That doesn't work because the field is called `nonpaddy`

File: Wflow/test/soil.jl [hunk 13]
```diff
@@ -41,13 +41,13 @@
         livestock = Wflow.NoDemandModel(; n),
         paddy = Wflow.PaddyModel(;
```
Comment (vers-w) [inline Wflow/test/soil.jl]: Is this test `"unit: update_bc_soil_model!"` completely based on a wflow (test) model? 

I would recommend that, so we have consistency between model parameters/variables. The `AllocationLandParameters` have empty vectors which is not correct.

Generally, my recommendation for a test that initializes different model components (or a substantial number of model variables/parameters in one model component) would be to base it completely on a wflow (test) model for consistency.

File: Wflow/test/soil.jl
Comment (vers-w) [inline Wflow/test/soil.jl:259]: Related to my previous comment, for test "unit: update_soil_water_storage! SbmSoilModel" I would recommend to completely base this on a wflow (test) model. It seems this was not done for the `demand` part (values are the same as in test `"unit: update_bc_soil_model!"`)?

**Review by vers-w — CHANGES_REQUESTED** [review]

File: Wflow/test/soil.jl [hunk 14]
```diff
@@ -2,72 +2,60 @@
...
 
     interception = Wflow.GashInterceptionModel(;
         parameters = Wflow.GashParameters(;
-            e_r = [0.1],
+            e_r = [0.25],
             vegetation_parameter_set = Wflow.VegetationParameters(;
                 leaf_area_index = nothing,
                 storage_wood = nothing,
                 kext = nothing,
                 storage_specific_leaf = nothing,
```
Comment (vers-w) [inline Wflow/test/soil.jl]: Most wflow (test) model use `leaf_area_index` climatology by default. If that's the case would be good to also specify values for these entries.

**Review by vers-w — APPROVED** [review]
LGTM, one small comment about `leaf_area_index` climatology. Would be good to update these entries if the wflow (test) model makes use of this climatology (default setting of hydromt_wflow and test models of Wflow.jl).
