### PR TITLE
Fix RutterInterception

### LINKED ISSUE #659: Bug in `RutterInterceptionModel` (has no `vegetation_parameter_set`)
### Wflow version checks

- [x] I have checked that this issue has not already been reported.

- [x] I have checked that this bug exists on the latest version of Wflow.

### Reproducible Example

When running a model on an hourly timestep, I get the error message that the `RutterInterceptionModel.parameters `has no `vegetation_parameter_set` , see the lines below:

https://github.com/Deltares/Wflow.jl/blob/cf377e7043f35d6a074648b60b94b67e81301756/Wflow/src/vegetation/canopy.jl#L111-L112

### Current behaviour

The way how the RutterInterceptionModel is slightly different from the GashInterceptionModel, which causes this issue. 

### Desired behaviour

Have a working interception model for both Gash and Rutter options. My current solution is to setup the RutterInterceptionModel in the same way (see linked PR)

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by JoostBuitink**
## Issue addressed
Fixes #659 

## Explanation
Explain how you addressed the bug/feature request, what choices you made and why.

## Checklist
- [ ] Updated tests or added new tests
- [ ] Branch is up to date with `master`
- [ ] Tests & pre-commit hooks pass
- [ ] Updated documentation if needed
- [ ] Updated changelog.qmd if needed

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

### CODE REVIEW

**Comment by vers-w** [comment]
Thanks for spotting this!
 
An alternative solution and I think a bit cleaner is to unpack differently in the `update!` function of the `RutterInterceptionModel`. In this case an additional `struct RutterParameters` is not required (including possible additional interception models that only make use of `VegetationParameters`). Also a change to the `function update_canopy_parameters!` is then needed (dispatch on `vegetation_parameter_set`).

File: Wflow/src/vegetation/canopy.jl [hunk 1]
```diff
@@ -131,16 +130,33 @@ function update!(model::RutterInterceptionModel, atmospheric_forcing::Atmospheri
...
+        storage_wood,
+        kext,
+        storage_specific_leaf,
+        canopygapfraction,
+        cmax,
+    )
+end
+
+"Update canopy parameters `cmax` and `canopygapfraction` based on `leaf_area_index` for a single timestep"
+function update_canopy_parameters!(model::AbstractInterceptionModel)
```
Comment (vers-w) [inline Wflow/src/vegetation/canopy.jl]: An alternative approach is to dispatch here on `VegetationParameters`, and adapt the function calls in lines 71 and 116. It is a bit shorter, also for possible additional interception models.

File: docs/changelog.qmd [hunk 2]
```diff
@@ -11,7 +11,8 @@ project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
 
 ### Fixed
 - Introduced in v1.0.0-rc1, fixed unit conversion model parameter `kv_0` to `kh_0` for
-  sub-daily model timestep. 
+  sub-daily model timestep.
+- Fix Rutter interception by correctly extracting the vegetation parameters.
```
Comment (vers-w) [inline docs/changelog.qmd]: Maybe also add here when this bug was introduced (v1.0.0-rc1)? 

For the official 1.0.0 release we can then easily remove these from the changelog.

**Review by vers-w — APPROVED** [review]
LGTM (made two small suggestions)!

File: docs/changelog.qmd (hunk 2 above)
Comment (JoostBuitink) [reply docs/changelog.qmd]: Good suggestion, I have added this!

File: Wflow/src/vegetation/canopy.jl (hunk 1 above)
Comment (JoostBuitink) [reply Wflow/src/vegetation/canopy.jl]: That is indeed a much cleaner solution! I went for this implementation now!
